package com.bitumen.bluefusion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FuelIssueanceTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelIssueanceTypeAllPropertiesEquals(FuelIssueanceType expected, FuelIssueanceType actual) {
        assertFuelIssueanceTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertFuelIssueanceTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelIssueanceTypeAllUpdatablePropertiesEquals(FuelIssueanceType expected, FuelIssueanceType actual) {
        assertFuelIssueanceTypeUpdatableFieldsEquals(expected, actual);
        assertFuelIssueanceTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelIssueanceTypeAutoGeneratedPropertiesEquals(FuelIssueanceType expected, FuelIssueanceType actual) {
        assertThat(actual)
            .as("Verify FuelIssueanceType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelIssueanceTypeUpdatableFieldsEquals(FuelIssueanceType expected, FuelIssueanceType actual) {
        assertThat(actual)
            .as("Verify FuelIssueanceType relevant properties")
            .satisfies(a -> assertThat(a.getFuelIssueTypeId()).as("check fuelIssueTypeId").isEqualTo(expected.getFuelIssueTypeId()))
            .satisfies(a -> assertThat(a.getFuelIssueType()).as("check fuelIssueType").isEqualTo(expected.getFuelIssueType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFuelIssueanceTypeUpdatableRelationshipsEquals(FuelIssueanceType expected, FuelIssueanceType actual) {
        // empty method
    }
}
