package com.bitumen.bluefusion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ManufacturerModelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManufacturerModelAllPropertiesEquals(ManufacturerModel expected, ManufacturerModel actual) {
        assertManufacturerModelAutoGeneratedPropertiesEquals(expected, actual);
        assertManufacturerModelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManufacturerModelAllUpdatablePropertiesEquals(ManufacturerModel expected, ManufacturerModel actual) {
        assertManufacturerModelUpdatableFieldsEquals(expected, actual);
        assertManufacturerModelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManufacturerModelAutoGeneratedPropertiesEquals(ManufacturerModel expected, ManufacturerModel actual) {
        assertThat(actual)
            .as("Verify ManufacturerModel auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManufacturerModelUpdatableFieldsEquals(ManufacturerModel expected, ManufacturerModel actual) {
        assertThat(actual)
            .as("Verify ManufacturerModel relevant properties")
            .satisfies(a -> assertThat(a.getModelId()).as("check modelId").isEqualTo(expected.getModelId()))
            .satisfies(a -> assertThat(a.getModelName()).as("check modelName").isEqualTo(expected.getModelName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertManufacturerModelUpdatableRelationshipsEquals(ManufacturerModel expected, ManufacturerModel actual) {
        // empty method
    }
}
