package com.bitumen.bluefusion.service.assetPlant.payload;

import com.bitumen.bluefusion.domain.enumeration.FuelType;
import com.bitumen.bluefusion.domain.enumeration.HorseOrTrailer;
import com.bitumen.bluefusion.domain.enumeration.SMRReaderType;

public record AssetPlantResponse(
    Long assetPlantId,
    String fleetNumber,
    String numberPlate,
    String fleetDescription,
    String owner,
    String chassisNumber,
    Integer yearOfManufacture,
    String colour,
    Integer currentSmrIndex,
    String engineNumber,
    String engineCapacityCC,
    String ledgerCode,
    Float tankCapacityLitres,
    Float capacityTons,
    Float capacityM3Loose,
    Float capacityM3Tight,
    Float maximumConsumption,
    Float minimumConsumption,
    Float maximumSmrOnFullTank,
    Boolean trackConsumption,
    Boolean trackSmrReading,
    Boolean requestWeeklyMileage,
    Boolean sent,
    String plantCategory,
    String plantSubcategory,
    String make,
    String model,
    HorseOrTrailer horseOrTrailer,
    SMRReaderType smrReaderType,
    FuelType fuelType,
    Boolean isPrimeMover,
    Boolean trackService,
    String currentContract,
    String currentLocation,
    String currentSite,
    String currentOperator,
    Boolean isActive
) {}
